/**
 * Lull DSP core — scipy-faithful signal processing for the drowsiness pipeline.
 *
 * PURE: no I/O, no platform deps, no wall-clock. Every numeric routine here is a
 * direct port of the operation used by the Phase-1 Python source of truth
 * (`tools/lull/sleepiness.py`, which relies on scipy.signal). The golden-vector
 * contract (`__tests__/golden/lull_vectors.json`) is the acceptance test.
 *
 * Why hand-rolled instead of leaning on fili's high-level helpers:
 *   - scipy.signal.butter designs an analog Butterworth prototype and maps it to
 *     digital via the bilinear transform with frequency pre-warping. fili's
 *     `bandpass` uses a center-frequency + bandwidth cascade with a different
 *     normalization, so its coefficients do NOT match scipy's. We reproduce
 *     scipy's exact design (zpk -> bilinear -> SOS -> filtfilt) so the golden
 *     vectors generated by scipy reproduce here within tolerance.
 *   - scipy.signal.welch uses an arbitrary nperseg DFT (no power-of-2 padding).
 *     fili's radix-2 FFT can't size to nperseg=1000, so we use a Bluestein FFT
 *     for the exact-length periodogram.
 */

// ---------------------------------------------------------------------------
// Complex FFT (Bluestein / chirp-z) — supports arbitrary length N.
// ---------------------------------------------------------------------------

/** In-place radix-2 Cooley–Tukey FFT. len(re)===len(im)===power of two. */
function fftRadix2(re: number[], im: number[]): void {
  const n = re.length;
  if (n <= 1) return;
  // bit-reversal permutation
  for (let i = 1, j = 0; i < n; i++) {
    let bit = n >> 1;
    for (; j & bit; bit >>= 1) j ^= bit;
    j ^= bit;
    if (i < j) {
      [re[i], re[j]] = [re[j], re[i]];
      [im[i], im[j]] = [im[j], im[i]];
    }
  }
  for (let len = 2; len <= n; len <<= 1) {
    const ang = (-2 * Math.PI) / len;
    const wr = Math.cos(ang);
    const wi = Math.sin(ang);
    for (let i = 0; i < n; i += len) {
      let curR = 1;
      let curI = 0;
      for (let k = 0; k < len / 2; k++) {
        const aR = re[i + k];
        const aI = im[i + k];
        const bR = re[i + k + len / 2] * curR - im[i + k + len / 2] * curI;
        const bI = re[i + k + len / 2] * curI + im[i + k + len / 2] * curR;
        re[i + k] = aR + bR;
        im[i + k] = aI + bI;
        re[i + k + len / 2] = aR - bR;
        im[i + k + len / 2] = aI - bI;
        const nextR = curR * wr - curI * wi;
        curI = curR * wi + curI * wr;
        curR = nextR;
      }
    }
  }
}

/**
 * Forward DFT of arbitrary length via Bluestein's algorithm.
 * Returns { re, im } of length n (full complex spectrum).
 */
export function dft(real: number[]): { re: number[]; im: number[] } {
  const n = real.length;
  // pick FFT size m = next power of two >= 2n-1
  let m = 1;
  while (m < 2 * n - 1) m <<= 1;

  // chirp: w_k = exp(-i*pi*k^2/n)
  const cosT = new Array<number>(n);
  const sinT = new Array<number>(n);
  for (let k = 0; k < n; k++) {
    // (k*k mod 2n) keeps the argument small for numerical stability
    const j = (k * k) % (2 * n);
    const ang = (Math.PI * j) / n;
    cosT[k] = Math.cos(ang);
    sinT[k] = Math.sin(ang);
  }

  const aR = new Array<number>(m).fill(0);
  const aI = new Array<number>(m).fill(0);
  for (let k = 0; k < n; k++) {
    aR[k] = real[k] * cosT[k];
    aI[k] = -real[k] * sinT[k];
  }

  const bR = new Array<number>(m).fill(0);
  const bI = new Array<number>(m).fill(0);
  bR[0] = cosT[0];
  bI[0] = sinT[0];
  for (let k = 1; k < n; k++) {
    bR[k] = bR[m - k] = cosT[k];
    bI[k] = bI[m - k] = sinT[k];
  }

  fftRadix2(aR, aI);
  fftRadix2(bR, bI);
  for (let k = 0; k < m; k++) {
    const xr = aR[k] * bR[k] - aI[k] * bI[k];
    const xi = aR[k] * bI[k] + aI[k] * bR[k];
    aR[k] = xr;
    aI[k] = xi;
  }
  // inverse FFT (conjugate trick)
  for (let k = 0; k < m; k++) aI[k] = -aI[k];
  fftRadix2(aR, aI);
  for (let k = 0; k < m; k++) {
    aR[k] = aR[k] / m;
    aI[k] = -aI[k] / m;
  }

  const re = new Array<number>(n);
  const im = new Array<number>(n);
  for (let k = 0; k < n; k++) {
    re[k] = aR[k] * cosT[k] + aI[k] * sinT[k];
    im[k] = -aR[k] * sinT[k] + aI[k] * cosT[k];
  }
  return { re, im };
}

// ---------------------------------------------------------------------------
// Helpers: detrend, mean, RMS.
// ---------------------------------------------------------------------------

export function mean(x: number[]): number {
  let s = 0;
  for (let i = 0; i < x.length; i++) s += x[i];
  return s / x.length;
}

/** scipy.signal.detrend(x, type='constant'): subtract the mean. */
export function detrendConstant(x: number[]): number[] {
  const m = mean(x);
  const out = new Array<number>(x.length);
  for (let i = 0; i < x.length; i++) out[i] = x[i] - m;
  return out;
}

// ---------------------------------------------------------------------------
// Butterworth design (matches scipy.signal.butter, output as second-order
// sections) + zero-phase forward/backward filtering (matches filtfilt).
// ---------------------------------------------------------------------------

interface Complex {
  re: number;
  im: number;
}

const cMul = (a: Complex, b: Complex): Complex => ({
  re: a.re * b.re - a.im * b.im,
  im: a.re * b.im + a.im * b.re,
});
const cAdd = (a: Complex, b: Complex): Complex => ({ re: a.re + b.re, im: a.im + b.im });
const cSub = (a: Complex, b: Complex): Complex => ({ re: a.re - b.re, im: a.im - b.im });
const cDiv = (a: Complex, b: Complex): Complex => {
  const d = b.re * b.re + b.im * b.im;
  return { re: (a.re * b.re + a.im * b.im) / d, im: (a.im * b.re - a.re * b.im) / d };
};

/** Expand monic polynomial from its complex roots: returns real coeffs (highest first). */
function polyFromRoots(roots: Complex[]): number[] {
  let coeffs: Complex[] = [{ re: 1, im: 0 }];
  for (const r of roots) {
    const next: Complex[] = new Array(coeffs.length + 1)
      .fill(0)
      .map(() => ({ re: 0, im: 0 }));
    for (let i = 0; i < coeffs.length; i++) {
      next[i] = cAdd(next[i], coeffs[i]); // * 1 (z term)
      next[i + 1] = cSub(next[i + 1], cMul(coeffs[i], r)); // * (-root)
    }
    coeffs = next;
  }
  return coeffs.map((c) => c.re);
}

interface TF {
  b: number[];
  a: number[];
}

/**
 * Design a digital Butterworth filter (lowpass/highpass/bandpass) exactly as
 * scipy.signal.butter does: analog prototype zpk -> frequency transform ->
 * bilinear transform. Wn entries are normalized to Nyquist (0..1). Returns
 * transfer-function coeffs {b, a}.
 */
export function butter(
  order: number,
  Wn: number | [number, number],
  btype: 'low' | 'high' | 'band'
): TF {
  // --- analog lowpass prototype: poles on unit circle, no finite zeros ---
  const protoPoles: Complex[] = [];
  for (let k = 0; k < order; k++) {
    const theta = (Math.PI * (2 * k + 1)) / (2 * order) + Math.PI / 2;
    protoPoles.push({ re: Math.cos(theta), im: Math.sin(theta) });
  }
  let z: Complex[] = [];
  let p: Complex[] = protoPoles.slice();
  let k = 1; // prototype gain (product of -poles for butterworth == 1)

  const fs = 2.0; // bilinear pre-warp uses fs=2 (scipy convention with Wn pre-warped)

  if (btype === 'low' || btype === 'high') {
    const wn = Wn as number;
    const warped = 2 * fs * Math.tan((Math.PI * wn) / fs);
    if (btype === 'low') {
      // lp2lp: s -> s/warped
      const degree = p.length - z.length;
      z = z.map((zz) => ({ re: zz.re * warped, im: zz.im * warped }));
      p = p.map((pp) => ({ re: pp.re * warped, im: pp.im * warped }));
      k = k * Math.pow(warped, degree);
    } else {
      // lp2hp: s -> warped/s
      const degree = p.length - z.length;
      const newZ: Complex[] = z.map((zz) => cDiv({ re: warped, im: 0 }, zz));
      const newP: Complex[] = p.map((pp) => cDiv({ re: warped, im: 0 }, pp));
      // gain: k * real(prod(-z)/prod(-p))
      let num: Complex = { re: 1, im: 0 };
      for (const zz of z) num = cMul(num, { re: -zz.re, im: -zz.im });
      let den: Complex = { re: 1, im: 0 };
      for (const pp of p) den = cMul(den, { re: -pp.re, im: -pp.im });
      k = k * cDiv(num, den).re;
      // add zeros at origin to bring degree up
      for (let i = 0; i < degree; i++) newZ.push({ re: 0, im: 0 });
      z = newZ;
      p = newP;
    }
  } else {
    // bandpass
    const [lo, hi] = Wn as [number, number];
    const warpedLo = 2 * fs * Math.tan((Math.PI * lo) / fs);
    const warpedHi = 2 * fs * Math.tan((Math.PI * hi) / fs);
    const bw = warpedHi - warpedLo;
    const wo = Math.sqrt(warpedLo * warpedHi);
    // lp2bp: s -> (s^2 + wo^2)/(bw*s)
    const degree = p.length - z.length;
    // scale poles/zeros: p_lp * bw/2
    const pScaled = p.map((pp) => ({ re: (pp.re * bw) / 2, im: (pp.im * bw) / 2 }));
    const newP: Complex[] = [];
    for (const ps of pScaled) {
      // p +/- sqrt(p^2 - wo^2)
      const p2: Complex = cSub(cMul(ps, ps), { re: wo * wo, im: 0 });
      const root = csqrt(p2);
      newP.push(cAdd(ps, root));
      newP.push(cSub(ps, root));
    }
    // zeros: existing scaled (none) -> map, then add `degree` zeros at origin
    const newZ: Complex[] = [];
    for (let i = 0; i < degree; i++) newZ.push({ re: 0, im: 0 });
    // gain: k * bw^degree
    k = k * Math.pow(bw, degree);
    z = newZ;
    p = newP;
  }

  // --- bilinear transform: s -> 2*fs*(z-1)/(z+1) ---
  const fs2 = 2 * fs;
  const zDigital: Complex[] = [];
  const pDigital: Complex[] = [];
  // bilinear: z_d = (fs2 + s)/(fs2 - s)
  for (const s of z) {
    zDigital.push(cDiv(cAdd({ re: fs2, im: 0 }, s), cSub({ re: fs2, im: 0 }, s)));
  }
  for (const s of p) {
    pDigital.push(cDiv(cAdd({ re: fs2, im: 0 }, s), cSub({ re: fs2, im: 0 }, s)));
  }
  // gain factor: k * real( prod(fs2 - z_s) / prod(fs2 - p_s) )
  let numG: Complex = { re: 1, im: 0 };
  for (const s of z) numG = cMul(numG, cSub({ re: fs2, im: 0 }, s));
  let denG: Complex = { re: 1, im: 0 };
  for (const s of p) denG = cMul(denG, cSub({ re: fs2, im: 0 }, s));
  let kd = k * cDiv(numG, denG).re;
  // zeros gained by bilinear: zeros at -1 to match pole count
  const fill = pDigital.length - zDigital.length;
  for (let i = 0; i < fill; i++) zDigital.push({ re: -1, im: 0 });

  // --- assemble transfer function ---
  const bComplex = polyFromRoots(zDigital);
  const aComplex = polyFromRoots(pDigital);
  const b = bComplex.map((c) => c * kd);
  const a = aComplex;
  return { b, a };
}

function csqrt(c: Complex): Complex {
  const r = Math.hypot(c.re, c.im);
  const re = Math.sqrt((r + c.re) / 2);
  let im = Math.sqrt((r - c.re) / 2);
  if (c.im < 0) im = -im;
  return { re, im };
}

/**
 * scipy.signal.iirnotch(w0, Q, fs): second-order IIR notch.
 * Returns {b, a}. w0 = mains_hz, fs = sampling rate.
 */
export function iirnotch(w0Hz: number, Q: number, fs: number): TF {
  const w0 = w0Hz / (fs / 2.0); // normalized to Nyquist (0..1)
  const bw = w0 / Q;
  const wpi = w0 * Math.PI;
  const bwpi = bw * Math.PI;
  const gb = 1 / Math.SQRT2;
  const beta = (Math.sqrt(1.0 - gb * gb) / gb) * Math.tan(bwpi / 2.0);
  const gain = 1.0 / (1.0 + beta);
  const b = [gain, -2.0 * Math.cos(wpi) * gain, gain];
  const a = [1.0, -2.0 * Math.cos(wpi) * gain, 2.0 * gain - 1.0];
  return { b, a };
}

// ---------------------------------------------------------------------------
// lfilter + filtfilt (Gustafsson-free, scipy default odd padlen).
// ---------------------------------------------------------------------------

/** Direct-form II transposed IIR filter (scipy.signal.lfilter, zi=0). */
function lfilter(b: number[], a: number[], x: number[], zi?: number[]): number[] {
  const n = Math.max(a.length, b.length);
  const bb = b.slice();
  const aa = a.slice();
  while (bb.length < n) bb.push(0);
  while (aa.length < n) aa.push(0);
  const a0 = aa[0];
  for (let i = 0; i < n; i++) {
    bb[i] /= a0;
    aa[i] /= a0;
  }
  const z = zi ? zi.slice() : new Array<number>(n - 1).fill(0);
  const y = new Array<number>(x.length);
  for (let m = 0; m < x.length; m++) {
    const xm = x[m];
    const ym = bb[0] * xm + z[0];
    y[m] = ym;
    for (let i = 1; i < n - 1; i++) {
      z[i - 1] = bb[i] * xm + z[i] - aa[i] * ym;
    }
    z[n - 2] = bb[n - 1] * xm - aa[n - 1] * ym;
  }
  return y;
}

/** Compute lfilter_zi: steady-state initial conditions (scipy.signal.lfilter_zi). */
function lfilterZi(b: number[], a: number[]): number[] {
  const n = Math.max(a.length, b.length);
  const bb = b.slice();
  const aa = a.slice();
  while (bb.length < n) bb.push(0);
  while (aa.length < n) aa.push(0);
  const a0 = aa[0];
  const bn = bb.map((v) => v / a0);
  const an = aa.map((v) => v / a0);
  const order = n - 1;
  // scipy.signal.lfilter_zi: solve (I - A) zi = B, where A is the companion
  // matrix of the (normalized) denominator and B[i] = bn[i+1] - an[i+1]*bn[0].
  const B: number[] = [];
  for (let i = 0; i < order; i++) B.push(bn[i + 1] - an[i + 1] * bn[0]);
  // Companion matrix C: first row = -an[1..], identity sub-diagonal below.
  const C: number[][] = [];
  for (let i = 0; i < order; i++) C.push(new Array<number>(order).fill(0));
  for (let j = 0; j < order; j++) C[0][j] = -an[j + 1];
  for (let i = 1; i < order; i++) C[i][i - 1] = 1;
  // Build (I - A) with A = C^T, then solve via Gaussian elimination.
  const A: number[][] = [];
  for (let i = 0; i < order; i++) {
    A.push(new Array<number>(order).fill(0));
    for (let j = 0; j < order; j++) {
      A[i][j] = (i === j ? 1 : 0) - C[j][i];
    }
  }
  return solveLinear(A, B);
}

/** Gaussian elimination with partial pivoting: solve A x = b. */
function solveLinear(Ain: number[][], bin: number[]): number[] {
  const n = bin.length;
  const A = Ain.map((row) => row.slice());
  const b = bin.slice();
  for (let col = 0; col < n; col++) {
    let piv = col;
    for (let r = col + 1; r < n; r++) {
      if (Math.abs(A[r][col]) > Math.abs(A[piv][col])) piv = r;
    }
    [A[col], A[piv]] = [A[piv], A[col]];
    [b[col], b[piv]] = [b[piv], b[col]];
    const d = A[col][col];
    if (Math.abs(d) < 1e-300) continue;
    for (let r = 0; r < n; r++) {
      if (r === col) continue;
      const f = A[r][col] / d;
      for (let c = col; c < n; c++) A[r][c] -= f * A[col][c];
      b[r] -= f * b[col];
    }
  }
  const x = new Array<number>(n);
  for (let i = 0; i < n; i++) x[i] = b[i] / A[i][i];
  return x;
}

/**
 * scipy.signal.filtfilt with default 'pad' method and odd extension.
 * padlen defaults to 3 * max(len(a), len(b)).
 */
export function filtfilt(b: number[], a: number[], x: number[]): number[] {
  // scipy default: padlen = 3 * max(len(a), len(b)).
  const ntaps = Math.max(a.length, b.length);
  const edge = 3 * ntaps;
  if (x.length <= edge) {
    // not enough data to pad; fall back to plain forward-backward without padding
    const zi0 = lfilterZi(b, a);
    const f = lfilter(b, a, x, zi0.map((v) => v * x[0]));
    const rev = f.slice().reverse();
    const zi1 = lfilterZi(b, a);
    const bk = lfilter(b, a, rev, zi1.map((v) => v * rev[0]));
    return bk.reverse();
  }
  // odd extension on both ends
  const ext: number[] = [];
  for (let i = edge; i >= 1; i--) ext.push(2 * x[0] - x[i]);
  for (let i = 0; i < x.length; i++) ext.push(x[i]);
  for (let i = x.length - 2; i >= x.length - 1 - edge; i--) ext.push(2 * x[x.length - 1] - x[i]);

  const zi = lfilterZi(b, a);
  // forward
  const fwd = lfilter(b, a, ext, zi.map((v) => v * ext[0]));
  // backward
  const rev = fwd.slice().reverse();
  const bwd = lfilter(b, a, rev, zi.map((v) => v * rev[0]));
  const y = bwd.reverse();
  // trim the extension
  return y.slice(edge, edge + x.length);
}

// ---------------------------------------------------------------------------
// High-level operations matching sleepiness.py.
// ---------------------------------------------------------------------------

/** Band-pass with detrend then zero-phase filtfilt. Mirrors `_bandpass`. */
export function bandpass(
  x: number[],
  fs: number,
  lo: number,
  hi: number,
  order: number
): number[] {
  const xd = detrendConstant(x);
  const nyq = fs / 2.0;
  const loN = Math.max(lo / nyq, 1e-4);
  const hiN = Math.min(hi / nyq, 0.99);
  const { b, a } = butter(order, [loN, hiN], 'band');
  return filtfilt(b, a, xd);
}

/** Notch at mains; skip if mains >= Nyquist. Mirrors `_notch`. */
export function notch(x: number[], fs: number, mainsHz: number, q: number): number[] {
  if (mainsHz <= 0 || mainsHz >= fs / 2.0) return x.slice();
  const { b, a } = iirnotch(mainsHz, q, fs);
  return filtfilt(b, a, x);
}

/**
 * Welch PSD with Hann window, 50% overlap, nperseg=min(len, max(fs*seg, min)).
 * Mirrors `_welch_psd` (scipy.signal.welch with detrend='constant').
 * Returns frequency bins and one-sided PSD.
 */
export function welchPsd(
  x: number[],
  fs: number,
  segSec: number,
  minSamples = 32
): { f: number[]; pxx: number[] } {
  const nperseg = Math.floor(Math.min(x.length, Math.max(fs * segSec, minSamples)));
  const noverlap = Math.floor(nperseg / 2); // scipy default for welch
  const step = nperseg - noverlap;

  // Hann window (scipy 'hann', sym=False -> periodic): w[n]=0.5-0.5cos(2*pi*n/M)
  const win = new Array<number>(nperseg);
  for (let i = 0; i < nperseg; i++) {
    win[i] = 0.5 - 0.5 * Math.cos((2 * Math.PI * i) / nperseg);
  }
  let winSqSum = 0;
  for (let i = 0; i < nperseg; i++) winSqSum += win[i] * win[i];
  const scale = 1.0 / (fs * winSqSum);

  const nfreq = Math.floor(nperseg / 2) + 1;
  const psdAccum = new Array<number>(nfreq).fill(0);
  let nSeg = 0;

  for (let start = 0; start + nperseg <= x.length; start += step) {
    const seg = x.slice(start, start + nperseg);
    // detrend constant
    const m = mean(seg);
    for (let i = 0; i < nperseg; i++) seg[i] = (seg[i] - m) * win[i];
    const { re, im } = dft(seg);
    for (let k = 0; k < nfreq; k++) {
      let p = (re[k] * re[k] + im[k] * im[k]) * scale;
      // one-sided: double all but DC and Nyquist
      if (k !== 0 && !(nperseg % 2 === 0 && k === nfreq - 1)) p *= 2;
      psdAccum[k] += p;
    }
    nSeg++;
  }
  if (nSeg === 0) {
    // window shorter than nperseg should not happen given the floor, but guard
    return { f: [0], pxx: [0] };
  }
  const pxx = psdAccum.map((v) => v / nSeg);
  const f = new Array<number>(nfreq);
  for (let k = 0; k < nfreq; k++) f[k] = (k * fs) / nperseg;
  return { f, pxx };
}

/** Trapezoidal band power over [lo, hi). Mirrors `_bandpower`. */
export function bandpower(f: number[], pxx: number[], lo: number, hi: number): number {
  const xs: number[] = [];
  const ys: number[] = [];
  for (let i = 0; i < f.length; i++) {
    if (f[i] >= lo && f[i] < hi) {
      xs.push(f[i]);
      ys.push(pxx[i]);
    }
  }
  if (xs.length === 0) return 0.0;
  // np.trapezoid(y, x)
  let area = 0;
  for (let i = 1; i < xs.length; i++) {
    area += ((ys[i] + ys[i - 1]) / 2) * (xs[i] - xs[i - 1]);
  }
  return area;
}

/** Spectral edge frequency at cumulative `pct` over [lo, hi]. Mirrors `_sef`. */
export function sef(
  f: number[],
  pxx: number[],
  lo: number,
  hi: number,
  pct: number
): number {
  const f2: number[] = [];
  const p2: number[] = [];
  for (let i = 0; i < f.length; i++) {
    if (f[i] >= lo && f[i] <= hi) {
      f2.push(f[i]);
      p2.push(pxx[i]);
    }
  }
  if (f2.length === 0) return 0.0;
  let total = 0;
  for (const v of p2) total += v;
  if (total <= 0) return 0.0;
  const c = new Array<number>(p2.length);
  let run = 0;
  for (let i = 0; i < p2.length; i++) {
    run += p2[i];
    c[i] = run / total;
  }
  // np.searchsorted(c, pct) -> first index where c[idx] >= pct
  let k = c.length;
  for (let i = 0; i < c.length; i++) {
    if (c[i] >= pct) {
      k = i;
      break;
    }
  }
  return f2[Math.min(k, f2.length - 1)];
}

/** High-pass RMS at cutoff `hz`; 0 if input is all-zero. Mirrors `_highpass_rms`. */
export function highpassRms(x: number[], fs: number, hz: number, order: number): number {
  let allZero = true;
  for (const v of x) {
    if (Math.abs(v) > 1e-12) {
      allZero = false;
      break;
    }
  }
  if (allZero) return 0.0;
  const m = mean(x);
  const xc = x.map((v) => v - m);
  const wn = Math.min(hz / (fs / 2.0), 0.99);
  const { b, a } = butter(order, wn, 'high');
  const y = filtfilt(b, a, xc);
  let ss = 0;
  for (const v of y) ss += v * v;
  return Math.sqrt(ss / y.length);
}
