/**
 * Golden-vector contract test for the Lull TS core.
 *
 * Loads the fixture generated by the Phase-1 Python source of truth
 * (`tools/lull/gen_golden.py` -> `lull_vectors.json`, copied here verbatim).
 * For each step it rebuilds the deterministic sinusoid window from the stored
 * generation PLAN (the identical formula in `gen_golden.segment`), runs the TS
 * SleepinessEstimator, and asserts:
 *   - |W_ts - W_python| <= 0.03 for every step
 *   - onset latches within +-3 steps of the Python fixture
 *   - the fixture actually reaches onset (otherwise the contract is vacuous)
 *
 * Runner: plain ts-node (no jest in this repo).
 *   npx ts-node --transpile-only --project scripts/tsconfig.scripts.json \
 *     src/lull/core/__tests__/golden.test.ts
 *
 * Exits non-zero on any failure so it can gate CI / pre-commit.
 */

import { SleepinessEstimator, LullParams } from '../sleepiness';
import vectors from './golden/lull_vectors.json';
import paramsJson from '../../lull_params.json';

const params = paramsJson as unknown as LullParams;

const W_TOL = 0.03;
const ONSET_STEP_TOL = 3;

interface Step {
  t: number;
  eeg_hz: number;
  eog_hz: number;
  eog_amp: number;
  W: number;
  onset: boolean;
}

/**
 * Rebuild one deterministic window from the generation plan. Identical to
 * gen_golden.segment: phase-0 sinusoids, no noise, fully cross-language
 * reproducible (no RNG).
 */
function segment(
  eegHz: number,
  eogHz: number,
  eogAmp: number,
  n: number,
  fs: number
): { fp: number[]; heog: number[] } {
  const fp = new Array<number>(n);
  const heog = new Array<number>(n);
  for (let i = 0; i < n; i++) {
    const t = i / fs;
    fp[i] = Math.sin(2 * Math.PI * eegHz * t);
    heog[i] = eogAmp * Math.sin(2 * Math.PI * eogHz * t);
  }
  return { fp, heog };
}

function main(): void {
  const fs: number = vectors.fs;
  const nPerWindow: number = vectors.n_per_window;
  const steps = vectors.steps as Step[];

  const est = new SleepinessEstimator(fs, params);

  let maxWDrift = 0;
  let worstStep = -1;
  let failures = 0;

  let pyOnsetStep = -1;
  let tsOnsetStep = -1;

  for (let i = 0; i < steps.length; i++) {
    const step = steps[i];
    const { fp, heog } = segment(step.eeg_hz, step.eog_hz, step.eog_amp, nPerWindow, fs);
    const out = est.update(fp, heog, step.t);

    const drift = Math.abs(out.W - step.W);
    if (drift > maxWDrift) {
      maxWDrift = drift;
      worstStep = i;
    }
    if (drift > W_TOL) {
      failures++;
      if (failures <= 10) {
        console.error(
          `  W drift FAIL @step ${i} (t=${step.t}): ts=${out.W.toFixed(6)} py=${step.W.toFixed(
            6
          )} |Δ|=${drift.toFixed(6)}`
        );
      }
    }

    if (step.onset && pyOnsetStep < 0) pyOnsetStep = i;
    if (out.onset && tsOnsetStep < 0) tsOnsetStep = i;
  }

  console.log('--- Lull golden-vector contract ---');
  console.log(`steps:              ${steps.length}`);
  console.log(`max |W| drift:      ${maxWDrift.toFixed(6)} @step ${worstStep} (tol ${W_TOL})`);
  console.log(`python onset step:  ${pyOnsetStep}`);
  console.log(`ts onset step:      ${tsOnsetStep}`);

  let ok = true;

  if (pyOnsetStep < 0) {
    console.error('FAIL: fixture never reaches onset — contract is vacuous.');
    ok = false;
  }
  if (failures > 0) {
    console.error(`FAIL: ${failures} step(s) exceeded W tolerance ${W_TOL}.`);
    ok = false;
  }
  if (tsOnsetStep < 0) {
    console.error('FAIL: TS estimator never latched onset.');
    ok = false;
  } else if (pyOnsetStep >= 0) {
    const onsetDelta = Math.abs(tsOnsetStep - pyOnsetStep);
    console.log(`onset step agreement: |Δ|=${onsetDelta} (tol ${ONSET_STEP_TOL})`);
    if (onsetDelta > ONSET_STEP_TOL) {
      console.error(`FAIL: onset step disagreement ${onsetDelta} > ${ONSET_STEP_TOL}.`);
      ok = false;
    }
  }

  if (ok) {
    console.log('PASS: TS core reproduces the Python golden vectors within tolerance.');
    process.exit(0);
  } else {
    console.error('GOLDEN TEST FAILED.');
    process.exit(1);
  }
}

main();
